import json, re, glob, os, sys
sys.stdout.reconfigure(encoding='utf-8')

# Comprehensive Romanian to English translation dictionary
# Format: exact phrases, sentences, words, and regexes

EXACT_TRANSLATIONS = {
    # Brand and Core terms
    "Știință. Ritual. Lumină.": "Science. Ritual. Light.",
    "Ştiinţă. Ritual. Lumină.": "Science. Ritual. Light.",
    "Science. Ritual. Light.": "Science. Ritual. Light.",
    "UNDE ȘTIINȚA": "WHERE SCIENCE",
    "DEVINE\nRITUAL": "BECOMES\nRITUAL",
    "UNDE ȘTIINȚA DEVINE RITUAL": "WHERE SCIENCE BECOMES RITUAL",
    "A MOMENT THAT BELONGS ONLY TO YOU.": "A MOMENT THAT BELONGS ONLY TO YOU.",
    "GOLDEN HOUR": "GOLDEN HOUR",
    "PĂSTREAZĂ LUMINA APROAPE DE TINE": "KEEP THE LIGHT CLOSE TO YOU",
    "DESCOPERĂ LUMINA": "DISCOVER LUMINA",
    "DESCOPERĂ LUMINA EUROPA": "DISCOVER LUMINA EUROPA",
    "Descoperă Lumina Europa": "Discover Lumina Europa",
    "Descoperă acum": "Discover Now",
    "DESCOPERĂ ACUM": "DISCOVER NOW",
    "Descoperă": "Discover",
    "DESCOPERĂ": "DISCOVER",
    "Cumpără acum": "Shop Now",
    "cumpără acum": "shop now",
    "CUMPĂRĂ ACUM": "SHOP NOW",
    "Cumpără Cadouri după Preț": "Shop Gifts by Price",
    "Cele Mai Vândute": "Bestsellers",
    "Vezi toate": "View All",
    "VEZI TOATE": "VIEW ALL",
    "Vezi Toate": "View All",
    "Vezi colecția": "View Collection",
    "EXPLOREAZĂ COLECȚIA": "EXPLORE THE COLLECTION",
    "Explorează Colecția": "Explore the Collection",
    "EXPLOREAZĂ TEHNOLOGIA": "EXPLORE THE TECHNOLOGY",
    "EXPLOREAZĂ TEHNOLOGIA →": "EXPLORE THE TECHNOLOGY →",
    "AFLĂ MAI MULTE": "LEARN MORE",
    "Află mai multe": "Learn more",
    "Află Mai Multe": "Learn More",
    "DESCOPERĂ MAI MULT": "DISCOVER MORE",
    "Descoperă mai mult": "Discover more",
    "VEZI GHIDUL VIDEO": "WATCH VIDEO GUIDE",
    "VEZI TOATE INGREDIENTELE": "VIEW ALL INGREDIENTS",
    "EXPLOREAZĂ CERCETAREA": "EXPLORE RESEARCH",
    "DESCOPERĂ PACHETELE DE RITUAL": "DISCOVER RITUAL BUNDLES",
    "DESCOPERĂ COLECȚIA LUMINA": "DISCOVER THE LUMINA COLLECTION",
    "INTRĂ ÎN LUMINA WORLD →": "ENTER LUMINA WORLD →",
    "DESCOPERĂ LUMINA WORLD": "DISCOVER LUMINA WORLD",
    "VIZIONEAZĂ FILMUL DE PREZENTARE": "WATCH THE BRAND FILM",
    "EXPLOREAZĂ MANIFESTUL": "EXPLORE THE MANIFESTO",
    "URMĂREȘTE CONVERSAȚIA": "WATCH CONVERSATION",
    "CITEȘTE TRANSCRIPTUL": "READ TRANSCRIPT",
    "TOATE CONVERSAȚIILE": "ALL CONVERSATIONS",
    "ULTIMELE CONVERSAȚII": "LATEST CONVERSATIONS",
    "EXPLOREAZĂ JURNALUL": "EXPLORE THE JOURNAL",
    "TRIMITE JURNALUL TĂU": "SUBMIT YOUR STORY",
    "TOATE ARTICOLELE": "ALL ARTICLES",
    "VEZI GALERIA ->": "VIEW GALLERY ->",
    "VEZI TOATĂ GALERIA": "VIEW FULL GALLERY",
    "TRIMITE FOTOGRAFIA TA": "SUBMIT YOUR PHOTO",
    "TRIMITE FOTOGRAFIA TA ->": "SUBMIT YOUR PHOTO ->",
    "VEZI TOATE PLATFORMELE ->": "VIEW ALL CHANNELS ->",
    "Devino membru LUMINA GOLDEN HOUR": "Become a LUMINA GOLDEN HOUR Member",
    "DESCOPERĂ GOLDEN REWARDS": "DISCOVER GOLDEN REWARDS",
    "ÎNSCRIE-TE ÎN COMUNITATE": "JOIN THE COMMUNITY",
    "DESCOPERĂ LUMINA GOLDEN HOUR →": "DISCOVER LUMINA GOLDEN HOUR →",
    "CONTACTEAZĂ-NE →": "CONTACT US →",
    "CONTACTEAZĂ-NE": "CONTACT US",
    "Contactează-ne": "Contact Us",
    
    # Golden Hour Sections
    "Ce este Golden Hour?": "What is Golden Hour?",
    "Beneficii": "Member Benefits",
    "Acces prioritar": "Priority Access",
    "Fii printre primii care descoperă noile lansări, colecțiile sezoniere și edițiile limitate Lumina.": "Be among the first to discover new launches, seasonal collections, and limited editions.",
    "Cadouri exclusive": "Exclusive Gifts",
    "Bucură-te de surprize și cadouri atent alese, create special pentru comunitatea Golden Hour.": "Enjoy thoughtfully curated surprises and complimentary gifts crafted especially for the Golden Hour community.",
    "Oferte dedicate": "Private Privileges",
    "Accesează beneficii și oferte disponibile exclusiv membrilor Golden Hour.": "Access private privileges and curated offers available exclusively to Golden Hour members.",
    "Ritualuri sezoniere": "Seasonal Rituals",
    "Primește recomandări și ritualuri adaptate nevoilor pielii tale, în armonie cu fiecare anotimp.": "Receive bespoke recommendations and rituals tailored to your skin's evolving seasonal needs.",
    "Lumina Journal": "Lumina Journal",
    "Descoperă articole, inspirație și povești despre frumusețea ritualurilor și îngrijirea conștientă a pielii.": "Discover editorial articles, inspiration, and reflections on the art of mindful skincare and rituals.",
    "Evenimente": "Private Events",
    "Primește invitații la lansări, experiențe și evenimente dedicate comunității Lumina.": "Receive personal invitations to exclusive launches, workshops, and Lumina community gatherings.",
    "Recomandări personalizate": "Tailored Guidance",
    "Inspiră-te din sugestii și ritualuri alese în funcție de sezon și de nevoile pielii tale.": "Find inspiration in curated skincare recommendations matched to your unique complexion.",
    "Experiențe înaintea tuturor": "First-Look Previews",
    "Testează în premieră produse și concepte noi și descoperă universul Lumina înainte de lansarea oficială.": "Experience preview access to emerging formulations and concepts before official release.",
    "Momente pe care nu le poți cumpăra": "Priceless Moments",
    "Ca membru Golden Hour, intri automat în selecția pentru experiențe și surprize create exclusiv pentru comunitatea Lumina.": "As a Golden Hour member, you are automatically eligible for bespoke experiences and surprises created exclusively for our community.",
    "Ritualul Lunii": "Ritual of the Month",
    "Un ritual complet Lumina, ales în funcție de sezon și nevoile pielii.": "A complete Lumina ritual curated for the season and your skin's specific needs.",
    "Colecția sezonului": "Seasonal Collection",
    "Primește în premieră ritualul care definește anotimpul.": "Receive early access to the signature ritual defining each season.",
    "Golden Box": "The Golden Box",
    "O selecție surpriză de produse și ediții speciale, disponibilă doar pentru comunitatea Golden Hour.": "A surprise curation of rare formulations and limited editions reserved for members.",
    "Experiențe Lumina": "Lumina Experiences",
    "Invitații la lansări, workshop-uri, evenimente private și întâlniri dedicate comunității.": "Invitations to masterclasses, private workshops, and intimate brand gatherings.",
    "Momente de răsfăț": "Moments of Indulgence",
    "Experiențe oferite împreună cu spa-uri și parteneri selectați.": "Bespoke treatments in collaboration with prestigious spas and luxury partners.",
    "O zi în universul Lumina": "A Day in the World of Lumina",
    "O experiență exclusivă alături de echipa Lumina, cu acces în culisele brandului, ședințe foto și testarea produselor înainte de lansare.": "An exclusive behind-the-scenes brand experience, photoshoots, and formulation previews.",
    "Comunitatea Lumina": "Lumina Community",
    "COMUNITATEA LUMINA": "LUMINA COMMUNITY",
    "Fiecare ritual spune o poveste": "Every Ritual Tells a Story",
    "În spatele fiecărui ritual există un moment de liniște, o intenție și o alegere de a pune grija pentru tine pe primul loc.": "Behind every ritual lies a quiet moment, an intention, and a conscious choice to prioritize self-care.",
    "Golden Hour este comunitatea celor care cred că frumusețea începe în aceste gesturi simple și continuă prin poveștile pe care le împărtășim împreună.": "Golden Hour is a sanctuary for those who believe true beauty begins with these gentle gestures and continues through the stories we share.",
    "MAI MULT DECÂT FRUMUSEȚE": "MORE THAN BEAUTY",
    "LUMINA GOLDEN HOUR": "LUMINA GOLDEN HOUR",
    "Un timp pe care ți-l oferi. Ritualuri, povești, experiențe și privilegii create pentru cei care aleg să facă din îngrijire un moment al lor.": "A time given to yourself. Rituals, stories, experiences, and privileges created for those who make skincare a mindful moment.",
    "Întrebări frecvente": "Frequently Asked Questions",
    "Este gratuit să fac parte din Golden Hour?": "Is membership in Golden Hour complimentary?",
    "Da. Înscrierea în comunitatea Lumina Golden Hour este complet gratuită.": "Yes. Joining the Lumina Golden Hour community is entirely complimentary.",
    "Cum mă pot înscrie?": "How do I join?",
    "Este suficient să îți creezi un cont sau să te înscrii folosind formularul de pe această pagină.": "Simply create an account or sign up using the invitation form on this page.",
    "Pot renunța oricând?": "Can I opt out at any time?",
    "Desigur. Te poți dezabona sau îți poți închide contul oricând dorești.": "Of course. You can unsubscribe or close your account at any time.",
    "Cum funcționează Golden Rewards?": "How does Golden Rewards work?",
    "Pe măsură ce faci parte din comunitate și alegi ritualurile Lumina, vei avea acces la beneficii, surprize și experiențe exclusive.": "As you immerse yourself in the Lumina universe, you automatically unlock refined rewards, surprises, and exclusive invitations.",
    "Povestea ta Lumina Golden Hour": "Your Lumina Golden Hour Journey",
    "Începutul ritualului.": "The Beginning of the Ritual.",
    "Intri în comunitatea Lumina și ai acces la lansări în premieră, inspirație, ritualuri și surprize pregătite pentru membrii Golden Hour.": "Enter the Lumina universe with first-look access to launches, inspiration, and member privileges.",
    "Afterglow": "Afterglow",
    "Lumina care rămâne.": "The Enduring Glow.",
    "Fidelitatea ta este răsplătită prin beneficii extinse, cadouri exclusive și acces prioritar la colecții și experiențe dedicate comunității.": "Your loyalty is rewarded with extended benefits, exclusive gifts, and priority invitations.",
    "First Light": "First Light",
    "Cel mai apropiat de universul Lumina.": "Closest to the Lumina Universe.",
    "Un nivel creat pentru cei care împărtășesc filosofia brandului și aleg să transforme fiecare ritual într-un moment de grijă. Beneficiezi de experiențe exclusive, invitații private și acces privilegiat la tot ceea ce urmează.": "A circle created for those who share our philosophy and transform every ritual into mindful care. Enjoy exclusive experiences, private invitations, and privileged access.",
    "Un loc unde grija pentru tine devine artă.": "Where mindful self-care becomes an art.",

    # Technology Page Sections
    "Tehnologia nanofibrelor Lumina oferă ingrediente active încapsulate cu precizie, puritate și scop bine definit.": "Lumina nanofiber technology delivers encapsulated active ingredients with precision, purity, and purpose.",
    "CĂLĂTORIA NANOFIBRELOR": "THE NANOFIBER JOURNEY",
    "Într-o lume\npe care nu o poți vedea.": "Into a realm\nbeyond the visible.",
    "O singură fibră. Mii de posibilități. Proiectată la nivel microscopic pentru a-ți transforma pielea la nivel uman.": "A single fiber. Countless possibilities. Engineered at the microscopic scale to transform your skin at the human scale.",
    "NĂSCUTĂ": "CREATED",
    "Creată cu precizie la scară nanometrică.": "Engineered with precision at the nanometric scale.",
    "ACTIVATĂ": "ACTIVATED",
    "Trezirea structurii cu apă sau spray hidratant.": "Awakening the matrix with water or hydrating facial mist.",
    "DIZOLVATĂ": "DISSOLVED",
    "Nanofibrele se dizolvă în câteva secunde, eliberând ingredientele active încapsulate.": "The nanofibers dissolve in seconds, releasing pure encapsulated actives.",
    "LIVRATĂ": "DELIVERED",
    "Substanțele active sunt livrate uniform și în profunzimea pielii.": "Active nutrients are evenly infused deep into the skin's surface layers.",
    "TRANSFORMATĂ": "TRANSFORMED",
    "Pielea este hidratată, revitalizată și vizibil reînnoită.": "Skin emerges deeply hydrated, revitalized, and visibly renewed.",
    "CUM FUNCȚIONEAZĂ": "HOW IT WORKS",
    "Cinci etape.\nO singură tehnologie inteligentă.": "Five stages.\nOne intelligent technology.",
    "ÎNCAPSULAT": "ENCAPSULATED",
    "Substanțele active sunt protejate în siguranță în matricea de nanofibre.": "Active compounds are shielded in a dry, preservative-free fiber matrix.",
    "ACTIVAT": "ACTIVATED",
    "Apa sau spray-ul hidratant activează matricea.": "Hydrating mist or water activates the structural matrix instantly.",
    "ELIBERAT": "RELEASED",
    "Fibrele se dizolvă, eliberând substanțele active.": "The fibers seamlessly dissolve, releasing pure bioactive nutrients.",
    "APLICAT": "APPLIED",
    "Formula aderă perfect și uniform pe piele.": "The formula fuses with the complexion for flawless second-skin adherence.",
    "EXPERIMENTAT": "EXPERIENCED",
    "Pielea se simte reînnoită, hidratată și luminoasă.": "The complexion reveals profound hydration, clarity, and renewed radiance.",
    "DE CE NANOFIBRE": "WHY NANOFIBERS",
    "PRECIZIE": "PRECISION",
    "Fibrele extrem de subțiri creează o potrivire ca o a doua piele pentru o livrare optimă.": "Ultra-fine fibers conform like a second skin for optimal, targeted nutrient delivery.",
    "PROSPEȚIME": "FRESHNESS",
    "Ingredientele active sunt protejate până în momentul exact al activării.": "Active ingredients are perfectly preserved dry until the exact moment of activation.",
    "EXPERIENȚĂ": "EXPERIENCE",
    "Tehnologia avansată întâlnește luxul senzorial în fiecare ritual.": "Cutting-edge biotechnology meets sensory luxury in every conscious ritual.",
    "TEHNOLOGIE & FORMULĂ": "TECHNOLOGY & FORMULATION",
    "Proiectat pentru puritate.\nCreat pentru performanță.": "Engineered for Purity.\nCrafted for Performance.",
    "Structura noastră exclusivă de nanofibre întâlnește ingrediente active de înaltă performanță, atent selecționate pentru puritatea, stabilitatea și compatibilitatea lor cu pielea.": "Our proprietary nanofiber structure converges with high-performance active ingredients, meticulously selected for their purity, clinical efficacy, and skin affinity.",
    "ACTIVE CU PURITATE RIDICATĂ": "HIGH-PURITY ACTIVES",
    "Selectate clinic pentru eficacitate maximă": "Clinically selected for maximum potency and skin compatibility",
    "LIVRARE STABILĂ": "STABLE DELIVERY",
    "Protejate în interiorul matricei de fibre": "Protected inside the preservative-free dry matrix",
    "AFINITATE PENTRU PIELE": "SKIN AFFINITY",
    "Biocompatibil, delicat, non-iritant": "Biocompatible, ultra-gentle, and non-irritating",
    "REZULTATE VIZIBILE": "VISIBLE RESULTS",
    "Piele hidratată, mai netedă și mai luminoasă": "Deeply replenished, smoother, and radiant skin",
    "INGREDIENTE": "INGREDIENTS",
    "Puternice. Pure. Cu un scop precis.": "Potent. Pure. Purposeful.",
    "Amplifică luminozitatea pielii": "Enhances skin radiance and luminosity",
    "Susține reînnoirea celulară a pielii": "Supports cellular renewal and skin vitality",
    "Calmează și hidratează pielea uscată": "Soothes and intensely hydrates dry skin",
    "Protecție antioxidantă intensă": "Intense antioxidant shield against environmental stressors",
    "Susține producția naturală de colagen": "Supports natural collagen synthesis and firmness",
    "Menține hidratarea și bariera cutanată": "Reinforces moisture barrier and skin comfort",
    "Uniformizează și luminează tonul pielii": "Evens skin tone and restores clarity",
    "Suport anti-îmbătrânire și lifting": "Advanced anti-aging support and firming",
    "Întărește bariera protectoare a pielii": "Fortifies the protective moisture barrier",
    "Aderență sporită a măștii pe ten": "Enhances second-skin mask adherence",
    "Hidratare profundă și efect de umplere": "Deep cellular hydration and plumping effect",
    "Piele netedă, catifelată și radiantă": "Refined, silky-smooth, and glowing skin",
    "Hidratare profundă și fermitate": "Deep replenishment and firmness support",
    "Reparare și regenerare cutanată": "Skin barrier repair and regeneration",
    "Regenerare și revitalizare a tenului": "Revitalizes complexion and microcirculation",
    "Calmant și reconfortant pentru piele": "Calms, comforts, and restores balance",
    "BAZĂ ȘTIINȚIFICĂ": "SCIENTIFIC FOUNDATION",
    "Susținut de știință.\nCondus de rezultate.": "Backed by Science.\nDriven by Results.",
    "Dezvoltată de NanoPharma, tehnologia noastră de nanofibre este susținută de cercetări riguroase, studii clinice și inovație continuă.": "Engineered in collaboration with NanoPharma, our nanofiber technology is backed by over a decade of rigorous research, clinical trials, and European patents.",
    "Evaluare clinică a măștii cu nanofibre realizată de un institut independent.": "Independent clinical evaluation of Lumina nanofiber performance.",
    "Dezvoltat de NANOPHARMA REPUBLICA CEHĂ": "Engineered by NANOPHARMA, CZECH REPUBLIC",
    "ANI DE CERCETARE": "YEARS OF BIOTECH RESEARCH",
    "Studii Clinice": "Clinical Studies & Patents",
    "MOD DE UTILIZARE": "HOW TO USE",
    "Un ritual simplu. Rezultate remarcabile.": "A Simple Ritual. Remarkable Results.",
    "DESFĂȘOARĂ": "UNFOLD",
    "Scoate masca din plic.": "Gently remove the dry mask from its protective pouch.",
    "ACTIVEAZĂ": "ACTIVATE",
    "Pulverizează cu apă sau Lumina Mist.": "Mist generously with pure water or Lumina Facial Mist.",
    "APLICĂ": "APPLY",
    "Așază pe fața curată și netezește delicat.": "Place seamlessly onto cleansed skin and smooth gently.",
    "RELAXEAZĂ-TE": "REST",
    "Relaxează-te timp de 15-20 de minute.": "Relax for 15–20 minutes as the actives absorb.",
    "ÎNDEPĂRTEAZĂ": "REMOVE",
    "Desprinde masca și arunc-o.": "Peel away the translucent mask layer.",
    "CONTINUĂ": "COMPLETE",
    "Tamponează ușor esența rămasă. Fără clătire.": "Gently pat remaining essence into skin. No rinsing required.",
    "FRECVENȚĂ RECOMANDATĂ": "RECOMMENDED FREQUENCY",
    "Alege-ți ritualul.<br>Urmează-ți ritmul.": "Choose Your Ritual.<br>Follow Your Rhythm.",
    "HIDRATARE": "HYDRATION",
    "De 2-3 ori pe săptămână": "2–3 times weekly",
    "De 1-2 ori pe săptămână": "1–2 times weekly",
    "Amplifică hidratarea și luminozitatea.": "Deeply replenishes moisture and luminous clarity.",
    "RECUPERARE": "RECOVERY",
    "Revigorează și fortifică bariera pielii.": "Soothes and reinforces the skin's moisture barrier.",
    "LUMINOZITATE": "RADIANCE",
    "Revitalizează tenul tern și obosit.": "Revitalizes tired, dull complexion with instant glow.",
    "REGENERARE": "REGENERATION",
    "Rafinează textura și tonul pielii.": "Refines texture and promotes youthful elasticity.",
    "SINERGII DE RITUAL": "RITUAL SYNERGIES",
    "O singură piele.<br>Mai mult de<br>o singură nevoie.": "One Complexion.<br>More Than<br>A Single Need.",
    "HIDRATEAZĂ": "HYDRATE",
    "CALMEAZĂ": "SOOTHE",
    "ILUMINEAZĂ": "BRIGHTEN",
    "REGENEREAZĂ": "RENEW",
    "DESCOPERĂ-ȚI RITUALUL": "DISCOVER YOUR RITUAL",
    "Fiecare moment.<br>Un ritual.": "Every Moment.<br>A Ritual.",
    "CLARITATE DE DIMINEAȚĂ": "MORNING CLARITY",
    "Trezire. Hidratare. Pregătește-ți pielea pentru ziua ce urmează.": "Awaken. Hydrate. Prepare your complexion for the day ahead.",
    "RECUPERARE DE SEARĂ": "EVENING RECOVERY",
    "Calm. Refacere. Eliberează tensiunea zilei și resetează tenul.": "Calm. Restore. Release daily tension and reset the skin overnight.",
    "RITUAL DE LUMINOZITATE": "RADIANCE RITUAL",
    "Strălucire. Rafinament. Pentru evenimente și momente speciale.": "Glow. Elegance. Perfect preparation for special occasions.",
    "RESETARE SĂPTĂMÂNALĂ": "WEEKLY RESET",
    "Detoxifiere. Reînnoire. Îngrijire profundă pentru un ten echilibrat.": "Purify. Renew. Deep holistic nourishment for balanced skin.",
    "CONFORT DE IARNĂ": "WINTER COMFORT",
    "Protecție. Hrănire. Apără-ți pielea împotriva intemperiilor.": "Protect. Nourish. Shield your barrier against harsh seasonal elements.",
    "TEHNOLOGIA CONTEAZĂ DOAR ATUNCI CÂND DEVINE PARTE DIN RITUALUL TĂU.": "TECHNOLOGY ONLY MATTERS WHEN IT BECOMES PART OF YOUR RITUAL.",

    # Lumina World Sections
    "FRUMUSEȚEA ARE MAI MULTE POVEȘTI": "BEAUTY HAS MANY STORIES",
    "LUMINA WORLD": "LUMINA WORLD",
    "Explorăm frumusețea dincolo de oglindă — prin știință, cultură, ritual, istorie, artă și oameni. Un loc pentru idei care merită mai mult decât câteva secunde de atenție.": "Exploring beauty beyond the mirror — through science, culture, ritual, history, art, and human connection. A home for ideas that deserve more than a few seconds of attention.",
    "BINE AI VENIT ÎN": "WELCOME TO",
    "Mai mult decât îngrijirea pielii.": "More than skincare.",
    "Un loc unde știința, cultura și viața trăită cu atenție se întâlnesc.": "Where science, culture, and mindful living converge.",
    "MANIFESTUL": "THE MANIFESTO",
    "O revistă digitală": "A digital publication",
    "cu un scop.": "with purpose.",
    "LUMINA WORLD este spațiul nostru editorial pentru idei care luminează. Un loc pentru conversații cu minți remarcabile, povești de la frontierele frumuseții și științei și inspirație pentru a trăi cu intenție.": "LUMINA WORLD is our editorial haven for illuminating ideas. A gathering place for conversations with visionary minds, stories from the frontiers of science and beauty, and inspiration to live with intention.",
    "Curatoriat cu grijă. Împărtășit cu un scop.": "Curated with care. Shared with purpose.",
    "CONVERSAȚIE ÎN PRIM-PLAN": "FEATURED CONVERSATION",
    "ȘTIINȚĂ ȘI LONGEVITATE": "SCIENCE & LONGEVITY",
    "Noua știință a longevității pielii": "The New Science of Skin Longevity",
    "O conversație cu Katerina, CEO NanoPharma, despre nanofibre, inovație și ce înseamnă să construiești tehnologie de frumusețe din interiorul științei.": "A dialogue with Kateřina, CEO of NanoPharma, on nanofibers, innovation, and crafting beauty technology from the heart of science.",
    "ȘTIINȚĂ": "SCIENCE",
    "CULTURĂ": "CULTURE",
    "OAMENI": "PEOPLE",
    "SUSTENABILITATE": "SUSTAINABILITY",
    "BUNĂSTARE": "WELLBEING",
    "EUROPA": "EUROPE",
    "MEȘTEȘUG": "CRAFT",
    "JURNAL": "JOURNAL",
    "FII PARTE DIN JURNAL": "JOIN THE JOURNAL",
    "Trimite Povestea Ta": "Submit Your Story",
    "Împărtășește propria ta perspectivă, experiență sau cercetare pentru a fi publicată în Jurnalul Lumina.": "Share your perspective, experience, or research to be featured in the Lumina Journal.",
    "PROIECT EDITORIAL SPECIAL": "SPECIAL EDITORIAL PROJECT",
    "Orașe diferite. Chipuri diferite. Povești diferite.": "Different cities. Different faces. Different stories.",
    "O singură Europă. Sub aceeași lumină.": "One Europe. Under the same light.",
    "LANSARE ÎN NOIEMBRIE 2026": "LAUNCHING NOVEMBER 2026",
    "ARTICOLE": "ARTICLES",
    "Idei. Perspective. Conversații care modelează lumea în care trăim.": "Ideas. Perspectives. Conversations shaping the world we inhabit.",
    "Umanitate\nîn Lumină": "Humanity\nin Light",
    "Umanitate în Lumină": "Humanity in Light",
    "SURPRINDE": "CAPTURE",
    "Momente autentice<br>din viața ta de zi cu zi.": "Authentic moments<br>from your daily life.",
    "SPUNE-NE UNDE": "LOCATE",
    "Oraș, țară<br>și câteva cuvinte.": "City, country<br>and a few words.",
    "TRIMITE": "SUBMIT",
    "Vom analiza și<br>te vom contacta.": "Our editorial team will<br>review and reach out.",
    "INSPIRĂ": "INSPIRE",
    "Povestea ta îi poate<br>inspira pe ceilalți.": "Your story can<br>inspire others.",
    "FII PARTE DIN POVESTE": "BE PART OF THE STORY",
    "Împărtășește Lumina": "Share The Light",
    "Trimite-ne momentele tale din întreaga Europă. Lumina pe care o vezi. Poveștile pe care le trăiești. Le putem include în galeria noastră.": "Send us your moments from across Europe. The light you see. The stories you live. We may feature them in our gallery.",
    "URMĂREȘTE LUMINA": "FOLLOW LUMINA",
    "Inspirație aleasă\ndin universul nostru.": "Curated inspiration\nfrom our universe.",
    "Conținut selectat cu grijă. Nu un flux automat.": "Thoughtfully selected content. Not an automated feed.",

    # Contact & About Pages
    "SĂ VORBIM": "LET'S TALK",
    "INTRĂ ÎN LUMINA": "ENTER THE WORLD OF LUMINA",
    "Pentru întrebări, colaborări, presă sau pur și simplu pentru a ne saluta — suntem aici.": "For inquiries, collaborations, press, or simply to say hello — our team is here for you.",
    "Specialiștii noștri sunt aici pentru a vă ajuta cu sfaturi și recomandări personalizate.": "Our skincare specialists are here to assist with tailored advice and ritual recommendations.",
    "FONDATOR & DIRECTOR ȘTIINȚIFIC": "FOUNDER & SCIENTIFIC DIRECTOR",
    "Specialist în Tehnologia Nanofibrelor": "Nanofiber Technology Specialist",
    "Pionier în sisteme avansate de livrare a ingredientelor": "Pioneer in advanced transdermal active delivery systems",
    "Expert in dermatologie și stiința pielii": "Expert in dermatology and skin physiology",
    
    # Quiz & Ritual Finder
    "Ten (Față)": "Face",
    "Ochi": "Eyes",
    "Gât": "Neck",
    "Decolteu": "Décolleté",
    "Calmare pentru Ten Sensibil": "Calming for Sensitive Skin",
    "Hidratare Profundă": "Deep Hydration",
    "Reîmprospătare (Mist)": "Refreshing Mist",
    "Eliminare Pete și Uniformizare": "Dark Spot Correction & Tone Evening",
    "Luminozitate Intensă": "Intense Radiance",
    "Prevenire Îmbătrânire": "Anti-Aging Prevention",
    "Anti-Aging Intensiv": "Intensive Anti-Aging",
    "Fermitate și Lifting": "Firming & Lifting",
    "Regenerare și Reparare": "Regeneration & Barrier Repair",
    "Revitalizare și Energie": "Revitalizing & Energizing",
    "Personalizează-ți îngrijirea": "Personalize Your Skincare",
    "Găsește-ți Ritualul Perfect": "Find Your Perfect Ritual",
    "Fiecare zonă a pielii tale are nevoi unice. Alege zona pe care vrei să o tratezi...": "Every area of your skin has unique needs. Select the area you wish to treat to discover your ideal ritual.",

    # Product Page & Microscope Explorer
    "Acolo unde începe lumina": "Where The Light Begins",
    "SUB MICROSCOP": "UNDER THE MICROSCOPE",
    "Știință pe care o poți vedea. Rezultate pe care le poți simți.": "Science you can see. Results you can feel.",
    "DERULAȚI PENTRU A EXPLORA": "SCROLL TO EXPLORE",
    "Structură de Nanofibre": "Nanofiber Matrix",
    "Livrare de Ingrediente": "Active Ingredient Delivery",
    "Penetrare în Piele": "Deep Skin Penetration",
    "Transformare Vizibilă": "Visible Transformation",
    "FORMAT FĂRĂ CONSERVANȚI": "PRESERVATIVE-FREE FORMAT",
    "Formatul nostru uscat elimină necesitatea parabenilor, parfumurilor adăugate și conservanților inutili - perfect pentru pielea sensibilă.": "Our dry format eliminates the need for parabens, synthetic fragrances, and unnecessary preservatives — ideal for sensitive skin.",
    "DIFUZIE ACTIVĂ PURĂ": "PURE ACTIVE DIFFUSION",
    "TEHNOLOGIE PATENTATĂ DE NANOFIBRE": "PATENTED NANOFIBER TECHNOLOGY",
    "TRANSFORMARE ÎN 5 MINUTE": "5-MINUTE TRANSFORMATION",
    "Transformarea în 5 minute": "5-Minute Transformation",
    "Volum. Hidratare. Strălucire.": "Plumping. Hydration. Radiance.",
    "Redă strălucirea și confortul": "Restores Radiance & Comfort",
    "Întărește și calmează": "Strengthens & Soothes",
    "Ten deshidratat și obosit": "Dehydrated & Fatigued Skin",
    "Înainte de evenimente speciale": "Before Special Occasions",
    "După călătorii sau zboruri lungi": "After Travel or Long Flights",
    "Când tenul tău are nevoie de o recuperare instantanee": "When skin needs instant recovery and glow",
    "PROMISIUNEA NOASTRĂ": "OUR PROMISE",
    "Continuă ritualul": "Continue the Ritual",
    "Colecție Măști": "Mask Collection",
    "Măști individuale": "Single Masks",
    "ÎNCEPE CU UN RITUAL": "BEGIN WITH A RITUAL",
    "5 MINUTE CARE SCHIMBĂ TOTUL. REZULTATE VIZIBILE CARE DUREAZĂ.": "5 MINUTES THAT CHANGE EVERYTHING. VISIBLE RESULTS THAT LAST.",
    "5 minute pentru a-ți transforma pielea": "5 minutes to transform your skin",
    "Hidratare intensă. Transformare vizibilă.": "Intense hydration. Visible transformation.",
    "Hidratare profundă și regenerare": "Deep hydration and renewal",
    "Cum se utilizează": "How to Use",
    "Cumpărate frecvent împreună": "Frequently Bought Together",
    "Cumpără cu": "Pair With",
    "S-ar putea să-ți placă și": "You May Also Like",
    "Produse înrudite": "Related Products",
    "Informații de livrare": "Shipping Information",
    "Ghid de mărimi": "Size Guide",
    "Ghid de îngrijire": "Care Guide",
    "LIVRARE GRATUITĂ": "COMPLIMENTARY SHIPPING",
    "Livrare gratuită": "Complimentary Shipping",
    "PLATĂ SECURIZATĂ": "SECURE CHECKOUT",
    "Plată securizată": "Secure Checkout",
    "Rambursare în termen de 30 de zile": "30-Day Returns",
    "2 ani garanție": "2-Year Quality Guarantee",
    "Garanția unei finalizări securizate": "Guaranteed Secure Checkout",
    "Fii recompensat de fiecare dată": "Be rewarded with every order",
    "Nu, mulțumesc": "No, thank you",
    "Poartă acum": "Shop Now",
    "Grăbește-te": "Hurry Up",
    "PÂNĂ LA 70% REDUCERE": "UP TO 70% OFF",
    "REDUCERI DE RĂMAS BUN": "SEASONAL SPECIALS",
    "Alătură-te clubului nostru exclusiv pentru a primi acces prioritar, cadouri speciale și oferte dedicate.": "Join our exclusive circle to receive priority access, private gifts, and curated privileges.",
    "Aveți o întrebare? Suntem aici să vă ajutăm.": "Have a question? Our skincare concierge is here to help.",
    "Bucurați-vă de livrare rapidă și asigurată direct la ușa dumneavoastră pentru toate comenzile.": "Enjoy fast, insured worldwide delivery directly to your door.",
    "Tranzacții 100% sigure prin intermediul procesatoarelor de plăți de top și criptare SSL avansată.": "100% secure transactions via industry-leading payment gateways with end-to-end SSL encryption."
}

# Regex replacements for HTML and complex phrases
REGEX_REPLACEMENTS = [
    (r'Alimentat de tehnologia avansată a nanofibrelor, Lumina Europa îți transformă ritualul.*?revitalizată\.',
     'Powered by advanced nanofiber technology, Lumina Europa transforms your skincare ritual into a moment of visible renewal. Experience deep hydration, refined texture, and a radiant glow designed to leave your skin refreshed, firm, and beautifully revitalized.'),
    (r'Prin electrofilare, ingredientele active sunt integrate într-o matrice uscată de nanofibre.*?în piele',
     'Through electrospinning, active ingredients are integrated into a dry nanofiber matrix that, upon contact with water, enables up to 92% transfer of active ingredients into the skin.'),
    (r'Fiecare ritual spune o poveste\. Iar fiecare alegere de a reveni în universul Lumina merită răsplătită\..*?universul nostru\.',
     'Every ritual tells a story. And every choice to return to the Lumina universe deserves recognition. Golden Rewards is our way of celebrating your presence in our community. As you explore new rituals, you unlock elevated privileges designed to make every experience truly exceptional.'),
    (r'Există un moment în fiecare zi în care lumina devine mai blândă, mai caldă și mai aproape de piele\..*?înaintea tuturor\.',
     'There is a moment each day when light turns softer, warmer, and closer to the skin. Lumina Golden Hour is the community of those who discover rituals, launches, and experiences before anyone else.'),
    (r'Golden Hour este acel moment al zilei în care lumina devine mai blândă, iar timpul pare să încetinească\..*?universul Lumina\.',
     'Golden Hour is that time of day when the light softens, and time seems to slow down. We created this community to preserve that same emotion: a sanctuary where every launch, every ritual, and every story arrives first to those who choose to be part of the Lumina universe.'),
    (r'Pielea ta se schimbă odată cu timpul, anotimpurile.*?completa reciproc\.',
     'Your skin evolves with time, the seasons, your environment, and life\'s rhythms. A thoughtful skincare ritual evolves alongside it. Lumina Europa masks are formulated to work in perfect synergy — each with a distinct purpose, all designed to complement each other seamlessly.'),
    (r'Dezvoltată de NanoPharma, tehnologia noastră de nanofibre este susținută de cercetări riguroase.*?inovație continuă\.',
     'Engineered in collaboration with NanoPharma, our nanofiber technology is backed by over a decade of rigorous research, clinical trials, and European patents.'),
    (r'Europa sub aceeași lumină este o călătorie prin Europa.*?construim împreună\.',
     'Europe Under the Same Light is a journey across Europe, told through the people who call it home. Starting in November 2026, the project walks the streets of European cities to listen, question, and discover what connects us across borders, languages, and generations.'),
    (r'Prin conversații intime pe stradă, portrete și povești autentice.*?construim împreună\.',
     'Through intimate street conversations, portraits, and authentic stories, we explore identity, belonging, beauty, culture, and the shared future we build together.'),
    (r'Totul pornește dintr-o atingere\.<br>Hydro Mist pregătește pielea.*?devine lumină\.',
     'It all begins with a touch.<br>Hydro Mist prepares the skin. The dry mask rests gently, and the nanofibers transform, releasing active ingredients in a refined, quiet, and precise ritual.<br>You don\'t just see technology. You see the moment skincare becomes light.'),
    (r'Tehnologia noastră patentată de nanofibre este proiectată pentru livrare precisă.*?ingredient pur\.',
     'Our patented nanofiber technology is engineered for precise delivery, activating upon contact with hydrated skin to ensure the maximum efficacy of every pure active ingredient.'),
    (r'Prin accesarea sau utilizarea site-ului Lumina Europa, sunteți de acord să respectați acești termeni.*?site-ului nostru\.',
     'By accessing or using the Lumina Europa website, you agree to comply with and be bound by these Terms and Conditions. Please review them carefully before using our platform.'),
    (r'Produsele noastre sunt formulate cu tehnologie avansată de nanofibre.*?pe piele curată și umedă\.',
     'Our formulations feature advanced nanofiber matrix biotechnology designed to deliver pure encapsulated active ingredients upon contact with cleansed, hydrated skin.')
]

def translate_text(text):
    if not isinstance(text, str) or not text:
        return text
    
    # Check exact match first
    if text in EXACT_TRANSLATIONS:
        return EXACT_TRANSLATIONS[text]
    
    # Check regexes
    for pat, repl in REGEX_REPLACEMENTS:
        text = re.sub(pat, repl, text, flags=re.DOTALL)
    
    # Check word/phrase replacements
    for ro, en in EXACT_TRANSLATIONS.items():
        if ro in text:
            text = text.replace(ro, en)
    
    return text

def translate_obj(obj):
    if isinstance(obj, dict):
        return {k: translate_obj(v) for k, v in obj.items()}
    elif isinstance(obj, list):
        return [translate_obj(v) for v in obj]
    elif isinstance(obj, str):
        return translate_text(obj)
    return obj

def process_json_file(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract leading comment if present
    comment = ''
    m = re.match(r'^(/\*.*?\*/\s*)', content, flags=re.DOTALL)
    if m:
        comment = m.group(1)
        content_json = content[len(comment):]
    else:
        content_json = content
        
    try:
        data = json.loads(content_json)
    except Exception as e:
        print(f'Error parsing {file_path}: {e}')
        return
        
    translated_data = translate_obj(data)
    new_json = json.dumps(translated_data, indent=2, ensure_ascii=False)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        if comment:
            f.write(comment + new_json + '\n')
        else:
            f.write(new_json + '\n')
    print(f'Translated: {os.path.basename(file_path)}')

print('Starting translation of JSON templates...')
for path in glob.glob('d:/Lumina/templates/**/*.json', recursive=True) + glob.glob('d:/Lumina/templates/*.json', recursive=True):
    process_json_file(path)
